language: node_js
node_js:
- 8.12.0
cache:
  directories:
  - node_modules
install:
- yarn install
script:
- yarn run lint
- yarn run travis-test
env:
  secure: d1eXn8LB/nBLsJxQ4D5ChUYYBnvLAij03BOpzoS4iEpP8ZIR8vVyYwX3JcRCl7h3ZrTh9dCZiKb0GDsyyLn/l1tJedyKiOW9NTKM2nmXN5rGKvN9jUZHmtYMygGbnZf1/xNxTryCvRQMSUjLFDr8zB+hge7R+fvVZ7/a7l7YPRcqEb/x4vmYj4YhGp4ohwp7oZh23IsRos+kELBDhY8q0lbdIXrQDMFrP4QqP1f4gksqAT+x6+S/7UJjWxkUxj7Xc7SXMz7Y/vB6DYKPzdQTlJRPlsefORpxxM7SYseIRZ08e59AJL33gGvnjuBqqj+M+n+5K9/G5PJrEsEtoI//bEt76jLz2qVXieQ/91HCXiJ/ZhwM8ibgI2MwmrqiOr65cgA4S2Fr+0UbzIQfzw18Vw+tU1oGCoZBtgh5hL/ntBKNDziDYj9/EElIRxNc4L76muGx6rR4vsfuyUkfBNQPtxwzDme5CifuVTOLacotuYCmHPjtiVLF04jX8vm2K+xZpDe0ZZKPWIiHV2hMY1ZiEZaoqySWNOXMFCNikZEoLu6PUCVE5doouczdEjLhn/GVTqBP7uMaDQfipkv1cs8dqWvXc5c/lyI1yVM2LvcBXeLhjdgAabLQm40Gy9iXhJPyILdhnBTKSWsoLOY6ndjyx2hXZ05pX6av0Cel/f01Jvg=
